#!/bin/bash
#
# Short:    Perform post-install checks
# Author:   Mark J Swift
# Version:  1.0.3
# Modified: 30-Apr-2017
#
#
# Called as follows (by Install as root):    
#   PostInstall

# need to pass volume

# ---

# assume that all scripts are in a subdirectory off the main project directory
GLB_sv_ProjectDirPath="$(dirname $(dirname ${0}))"

# Include the CommonLib
. "${GLB_sv_ProjectDirPath}/inc/Common.sh"

# Exit if something went wrong unexpectedly
if test -z "${GLB_sv_ProjectName}"
then
  exit 90
fi

# ---

# Exit if not the root user
if [ "${GLB_sv_ThisUserName}" != "root" ]
then
  GLB_nf_logmessage ${GLB_iv_MsgLevelErr} "Unable to run, try: sudo ${GLB_sv_ThisScriptName}"
  exit 91
fi

# ---

# Where we should install
sv_RootDirPath="${1}"

if [ "${sv_RootDirPath}" = "/" ]
then
  sv_RootDirPath=""
fi

# ---

GLB_nf_logmessage ${GLB_iv_MsgLevelInfo} "Performing post-install checks"

if test -z "${sv_RootDirPath}"
then
  # Load LaunchDaemon plists
  while read sv_LaunchServiceFileName
  do
    GLB_nf_logmessage ${GLB_iv_MsgLevelNotice} "Loading LaunchDaemon file ${sv_LaunchServiceFileName}"
    launchctl load /Library/LaunchDaemons/${sv_LaunchServiceFileName}
  done < <(ls -1 /Library/LaunchDaemons | grep "${GLB_sv_ProjectSignature}")

  sv_UserName=$(stat -f '%Su' /dev/console)
  if [ "${sv_UserName}" != "root" ]
  then
    # Load LaunchAgent plists
    while read sv_LaunchServiceFileName
    do
      GLB_nf_logmessage ${GLB_iv_MsgLevelNotice} "Loading LaunchAgent file ${sv_LaunchServiceFileName} for user ${sv_UserName}"
      sudo -u ${sv_UserName} launchctl load /Library/LaunchAgents/${sv_LaunchServiceFileName}
    done < <(ls -1 /Library/LaunchAgents | grep "${GLB_sv_ProjectSignature}")
  fi

fi

# ---

GLB_nf_logmessage ${GLB_iv_MsgLevelInfo} "${GLB_sv_ProjectName} installed OK."

exit 0

