#!/bin/bash
#
# Short:    Do something when the primary network comes up or changes
# Author:   Mark J Swift
# Version:  1.0.2
# Modified: 04-Jan-2017
#
# Called by NetworkStatusWarden as follows:    
#   NetworkStatusWarden-NetworkUp <InterfaceName>

# ---

sv_PrimaryInterface="${1}"

say "Network up - $(echo "${sv_PrimaryInterface}" | sed "s|\(.\)|\1 |g")"
